[build]
  command = "dotnet publish src/NexaCRM.WebClient/NexaCRM.WebClient.csproj -c Release -o temp"
  publish = "temp/wwwroot"

[build.environment]
  DOTNET_CLI_TELEMETRY_OPTOUT = "1"
  DOTNET_NOLOGO = "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


