[build]
  command = "dotnet publish src/Web/NexaCRM.WebClient/NexaCRM.WebClient.csproj -c Release -o publish"
  publish = "publish"  # "publish/wwwroot"에서 "publish"로 변경

[build.environment]
  DOTNET_CLI_TELEMETRY_OPTOUT = "1"
  DOTNET_NOLOGO = "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
