[build]
  command = "dotnet publish src/Web/NexaCRM.WebClient/NexaCRM.WebClient.csproj -c Release"
  publish = "src/Web/NexaCRM.WebClient/bin/Release/net8.0/publish/wwwroot"

[build.environment]
  DOTNET_CLI_TELEMETRY_OPTOUT = "1"
  DOTNET_NOLOGO = "true"

[build.lifecycle]
  onBuild = """
    wget https://dot.net/v1/dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --channel 8.0
    export PATH=$HOME/.dotnet:$PATH
    dotnet --version
  """