-- Sample data for db_customers table
-- This provides test data for database customer management features
-- Status values must match DbStatus enum: New, InProgress, NoAnswer, Completed, OnHold

-- First, clear any existing sample data
DELETE FROM db_customers WHERE contact_id BETWEEN 1001 AND 1015;

INSERT INTO db_customers (
  contact_id,
  customer_name,
  contact_number,
  "group",
  assigned_to,
  assigner,
  assigned_date,
  last_contact_date,
  status,
  is_starred,
  is_archived,
  gender,
  address,
  region,
  status_detail,
  consultation_count,
  purchase_amount,
  notes,
  tags,
  referral_source,
  last_updated_by
) VALUES
-- VIP 고객들
(
  1001,
  '김민수',
  '010-1234-5678',
  'VIP',
  'manager@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '30 days',
  NOW() - INTERVAL '2 days',
  'Completed',
  true,
  false,
  'Male',
  '서울시 강남구 테헤란로 123',
  'Seoul',
  '우수 고객, 지속적인 관리 필요',
  15,
  15000000.00,
  '장기 고객, 매우 만족도 높음. 프리미엄 서비스 이용 중.',
  'VIP,장기고객,프리미엄',
  'Website',
  'manager@nexa.test'
),
(
  1002,
  '이지은',
  '010-2345-6789',
  'VIP',
  'sales@nexa.test',
  'manager@nexa.test',
  NOW() - INTERVAL '45 days',
  NOW() - INTERVAL '1 day',
  'InProgress',
  true,
  false,
  'Female',
  '서울시 서초구 서초대로 456',
  'Seoul',
  '최상위 고객, 정기 미팅 진행 중',
  22,
  28000000.00,
  '기업 대표, 추가 서비스 확장 논의 중.',
  'VIP,기업,확장가능',
  'Referral',
  'sales@nexa.test'
),
(
  1003,
  '박지훈',
  '010-3456-7890',
  'VIP',
  'manager@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '60 days',
  NOW() - INTERVAL '5 days',
  'InProgress',
  true,
  false,
  'Male',
  '경기도 성남시 분당구 판교로 789',
  'Gyeonggi',
  'IT 기업 CEO, 장기 계약 체결',
  18,
  20000000.00,
  '기술 관련 문의 많음. 전문적인 대응 필요.',
  'VIP,IT,기업',
  'Conference',
  'manager@nexa.test'
),

-- 일반 활성 고객들
(
  1004,
  '최수진',
  '010-4567-8901',
  'Standard',
  'sales@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '20 days',
  NOW() - INTERVAL '3 days',
  'InProgress',
  false,
  false,
  'Female',
  '서울시 마포구 월드컵북로 321',
  'Seoul',
  '일반 고객, 정기 서비스 이용',
  8,
  3500000.00,
  '마케팅 분야 종사, 추가 서비스 관심 보임.',
  'Standard,마케팅',
  'Social Media',
  'sales@nexa.test'
),
(
  1005,
  '정민호',
  '010-5678-9012',
  'Standard',
  'develop@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '7 days',
  'Completed',
  false,
  false,
  'Male',
  '부산시 해운대구 해운대로 654',
  'Busan',
  '스타트업 운영 중',
  5,
  2800000.00,
  '기술 지원 요청 빈번. 개발팀과 협력 중.',
  'Standard,스타트업,기술지원',
  'Website',
  'develop@nexa.test'
),
(
  1006,
  '강서영',
  '010-6789-0123',
  'Standard',
  'sales@nexa.test',
  'manager@nexa.test',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '4 days',
  'New',
  false,
  false,
  'Female',
  '인천시 연수구 송도과학로 987',
  'Incheon',
  '신규 고객, 적응 기간',
  3,
  1500000.00,
  '교육 분야 사업. 초기 단계 지원 필요.',
  'Standard,교육,신규',
  'Email Campaign',
  'sales@nexa.test'
),

-- 잠재 고객들 (Prospect)
(
  1007,
  '윤태희',
  '010-7890-1234',
  'Prospect',
  'sales@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days',
  'New',
  false,
  false,
  'Male',
  '대전시 유성구 대학로 147',
  'Daejeon',
  '잠재 고객, 상담 진행 중',
  1,
  0.00,
  '서비스 도입 검토 중. 예산 협의 필요.',
  'Prospect,검토중',
  'Cold Call',
  'sales@nexa.test'
),
(
  1008,
  '한지민',
  '010-8901-2345',
  'Prospect',
  'develop@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days',
  'New',
  false,
  false,
  'Female',
  '광주시 북구 첨단과학로 258',
  'Gwangju',
  '기술 데모 요청',
  2,
  0.00,
  '제품 시연 후 긍정적 반응. 추가 미팅 예정.',
  'Prospect,데모완료',
  'Webinar',
  'develop@nexa.test'
),

-- 비활성 고객들
(
  1009,
  '오준석',
  '010-9012-3456',
  'Standard',
  'sales@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '90 days',
  NOW() - INTERVAL '60 days',
  'NoAnswer',
  false,
  false,
  'Male',
  '울산시 남구 삼산로 369',
  'Ulsan',
  '장기 미사용, 재활성화 필요',
  7,
  4200000.00,
  '마지막 접촉 후 2개월 경과. 재연락 시도 필요.',
  'Inactive,재활성화대상',
  'Website',
  'sales@nexa.test'
),
(
  1010,
  '송하은',
  '010-0123-4567',
  'Standard',
  'manager@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '120 days',
  NOW() - INTERVAL '90 days',
  'OnHold',
  false,
  false,
  'Female',
  '대구시 수성구 동대구로 741',
  'Daegu',
  '서비스 중단 고객',
  4,
  1800000.00,
  '가격 문제로 서비스 중단. 프로모션 제안 검토.',
  'Inactive,가격민감',
  'Referral',
  'manager@nexa.test'
),

-- 보관된 고객들
(
  1011,
  '임소라',
  '010-1111-2222',
  'Standard',
  'sales@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '180 days',
  NOW() - INTERVAL '180 days',
  'OnHold',
  false,
  true,
  'Female',
  '제주도 제주시 연동 852',
  'Jeju',
  '이탈 고객, 보관 처리',
  2,
  800000.00,
  '경쟁사로 이동. 향후 재영입 고려.',
  'Churned,경쟁사이동',
  'Cold Call',
  'sales@nexa.test'
),
(
  1012,
  '배성민',
  '010-2222-3333',
  'VIP',
  'manager@nexa.test',
  'manager@nexa.test',
  NOW() - INTERVAL '200 days',
  NOW() - INTERVAL '150 days',
  'OnHold',
  false,
  true,
  'Male',
  '서울시 종로구 종로 963',
  'Seoul',
  '과거 VIP 고객, 사업 종료',
  12,
  12000000.00,
  '사업 정리로 서비스 종료. 좋은 관계 유지.',
  'Churned,사업종료',
  'Referral',
  'manager@nexa.test'
),

-- 추가 활성 고객들
(
  1013,
  '서준영',
  '010-3333-4444',
  'Standard',
  'develop@nexa.test',
  'manager@nexa.test',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '1 day',
  'InProgress',
  true,
  false,
  'Male',
  '서울시 송파구 올림픽로 753',
  'Seoul',
  '기술 지원 우수 고객',
  10,
  5500000.00,
  '개발 관련 피드백 많이 제공. 베타 테스터로 활용.',
  'Standard,기술피드백,베타테스터',
  'Partner',
  'develop@nexa.test'
),
(
  1014,
  '노유진',
  '010-4444-5555',
  'Standard',
  'sales@nexa.test',
  'sales@nexa.test',
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '6 days',
  'Completed',
  false,
  false,
  'Female',
  '경기도 수원시 팔달구 효원로 159',
  'Gyeonggi',
  '만족도 높은 고객',
  6,
  3200000.00,
  '추천 프로그램 참여 의향 있음.',
  'Standard,추천가능',
  'Social Media',
  'sales@nexa.test'
),
(
  1015,
  '홍재훈',
  '010-5555-6666',
  'VIP',
  'manager@nexa.test',
  'manager@nexa.test',
  NOW() - INTERVAL '75 days',
  NOW() - INTERVAL '3 days',
  'InProgress',
  true,
  false,
  'Male',
  '서울시 영등포구 여의대로 357',
  'Seoul',
  '금융업 종사, 대규모 계약',
  20,
  25000000.00,
  '금융권 인맥 보유. 추가 고객 소개 가능성.',
  'VIP,금융,네트워크',
  'Conference',
  'manager@nexa.test'
);

-- 연락처 ID에 대한 주석
COMMENT ON COLUMN db_customers.contact_id IS 'Reference to contacts table. Sample data uses IDs 1001-1015 for testing purposes.';
